language: python
python:
  - 3.6
services:
  - docker
install:
  - pip install -r requirements-test.txt
  - docker build -t max-facial-emotion-classifier .
  - docker run -it -d --rm -p 5000:5000 max-facial-emotion-classifier
before_script:
  - flake8 . --max-line-length=127
  - sleep 30
script:
  - pytest tests/test.py
