language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-facial-emotion-classifier .
  - docker run -it -d --rm -p 5000:5000 max-facial-emotion-classifier
before_script:
  - pip install pytest requests
  - sleep 30
script:
  - pytest tests/test.py
