apiVersion: v1
kind: Service
metadata:
  name: max-facial-emotion-classifier
spec:
  selector:
    app: max-facial-emotion-classifier

  ports:
  - port: 5000
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: max-facial-emotion-classifier
  labels:
    app: max-facial-emotion-classifier

spec:
  selector:
    matchLabels:
      app: max-facial-emotion-classifier
  
  replicas: 1
  template:
    metadata:
      labels:
        app: max-facial-emotion-classifier
    
    spec:
      containers:
      - name: max-facial-emotion-classifier
  
        image: codait/max-facial-emotion-classifier
    :latest
        ports:
        - containerPort: 5000
